#!/usr/bin/env bash
# Install udev rules so Marv peripherals keep stable paths across reboots / USB reorder.
#
# After editing vendor/product IDs below, run:
#   sudo ./setup_hardware_rules.sh
#   sudo udevadm control --reload-rules && sudo udevadm trigger
# Unplug/replug USB devices (or reboot), then verify:
#   ls -l /dev/ping_sonar /dev/explore_hd /dev/ark_fpv
#
# ---------------------------------------------------------------------------
# HOW TO FIND YOUR idVendor AND idProduct
# ---------------------------------------------------------------------------
#
# 1) Ping sonar (FTDI USB–serial) and ARK FPV (ArduPilot CDC):
#      lsusb
#    Example lines:
#      Bus 001 Device 007: ID 0403:6015 Future Technology Devices International, Ltd Bridge
#      Bus 001 Device 010: ID 1209:5740 Generic ARK_FPV
#    idVendor = first 4 hex digits (0403, 1209)
#    idProduct = second 4 hex digits (6015, 5740)
#
# 2) exploreHD camera (UVC):
#      v4l2-ctl --list-devices
#    Find the "exploreHD USB Camera" group. The MJPEG node is usually the
#    first /dev/video* in that group (often video0). Then:
#      udevadm info -a -n /dev/video0 | grep -E 'idVendor|idProduct|index'
#    Use idVendor/idProduct from the parent USB device. Keep ATTR{index}=="0"
#    so the symlink targets the MJPEG capture node, not the metadata/H.264 nodes.
#
# 3) Optional — stable serial by-id strings (more specific than vendor/product):
#      ls -la /dev/serial/by-id/
#
# ---------------------------------------------------------------------------

set -euo pipefail

RULES_FILE="/etc/udev/rules.d/99-marv-hardware.rules"

# --- EDIT THESE for your bench (defaults match a typical Marv Jetson setup) ---

# Blue Robotics Ping1D (FTDI FT231X UART bridge)
PING_VENDOR="0403"
PING_PRODUCT="6015"
# Optional: set to your FTDI serial from `ls -la /dev/serial/by-id/` or leave empty
PING_SERIAL=""   # e.g. DP05ILCR

# Blue Robotics exploreHD (UVC; often reports as Microdia 0c45:6366)
EXPLOREHD_VENDOR="0c45"
EXPLOREHD_PRODUCT="6366"
# UVC index 0 = primary capture node (MJPEG for OpenCV)
EXPLOREHD_VIDEO_INDEX="0"

# ARK FPV flight controller (ArduPilot USB MAVLink — interface 00 / if00)
ARK_VENDOR="1209"
ARK_PRODUCT="5740"

# ---------------------------------------------------------------------------

if [[ "${EUID}" -ne 0 ]]; then
  echo "Re-run with sudo: sudo $0"
  exit 1
fi

PING_RULE="SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"${PING_VENDOR}\", ATTRS{idProduct}==\"${PING_PRODUCT}\""
if [[ -n "${PING_SERIAL}" ]]; then
  PING_RULE+=", ATTRS{serial}==\"${PING_SERIAL}\""
fi
PING_RULE+=", SYMLINK+=\"ping_sonar\", GROUP=\"dialout\", MODE=\"0660\""

ARK_RULE="SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"${ARK_VENDOR}\", ATTRS{idProduct}==\"${ARK_PRODUCT}\", ATTRS{bInterfaceNumber}==\"00\", SYMLINK+=\"ark_fpv\", GROUP=\"dialout\", MODE=\"0660\""

CAMERA_RULE="SUBSYSTEM==\"video4linux\", KERNEL==\"video[0-9]*\", ATTR{index}==\"${EXPLOREHD_VIDEO_INDEX}\", ATTRS{idVendor}==\"${EXPLOREHD_VENDOR}\", ATTRS{idProduct}==\"${EXPLOREHD_PRODUCT}\", SYMLINK+=\"explore_hd\", GROUP=\"video\", MODE=\"0660\""

cat > "${RULES_FILE}" <<EOF
# Marv AUV — stable device symlinks (generated by setup_hardware_rules.sh)
# Ping1D  -> /dev/ping_sonar
${PING_RULE}

# exploreHD MJPEG node -> /dev/explore_hd
${CAMERA_RULE}

# ARK FPV MAVLink (if00) -> /dev/ark_fpv  (MAVProxy --master, not MAVROS)
${ARK_RULE}
EOF

chmod 644 "${RULES_FILE}"
udevadm control --reload-rules
udevadm trigger

echo ""
echo "Installed ${RULES_FILE}"
echo ""
echo "Symlinks (after replug USB):"
echo "  /dev/ping_sonar   — Ping1D serial"
echo "  /dev/explore_hd   — exploreHD MJPEG camera"
echo "  /dev/ark_fpv      — ARK FPV MAVLink (tty)"
echo ""
echo "Verify:"
echo "  ls -l /dev/ping_sonar /dev/explore_hd /dev/ark_fpv"
echo ""
echo "MAVProxy master (serial): /dev/ark_fpv"
echo "MAVROS fcu_url (UDP):     udp://@127.0.0.1:14555"
echo "Start bridge:             ~/marv_ws/start_telemetry_bridge.sh"
