#!/usr/bin/env bash
# mavlink-router telemetry splitter (lighter alternative to MAVProxy).
#
# Routes FCU serial -> MAVROS (127.0.0.1:14555) + QGC (listen 0.0.0.0:14550).
# MAVROS fcu_url: udp://@127.0.0.1:14555
#
# Install (Jetson / Ubuntu):
#   sudo apt update
#   sudo apt install mavlink-router
#
# If the package is unavailable, build from source:
#   https://github.com/mavlink-router/mavlink-router
#
# Ping (/dev/ping_sonar) and exploreHD (/dev/explore_hd): setup_hardware_rules.sh
set -euo pipefail

# ---------------------------------------------------------------------------
# FCU serial — USB (ARK FPV) or Jetson 40-pin UART
# ---------------------------------------------------------------------------
if [[ -z "${FCU_DEVICE:-}" ]]; then
  if [[ -e /dev/ark_fpv ]]; then
    FCU_DEVICE="$(readlink -f /dev/ark_fpv)"
  elif compgen -G "/dev/serial/by-id/usb-ArduPilot_ARK_FPV*-if00" >/dev/null; then
    FCU_DEVICE="$(readlink -f "$(ls -1 /dev/serial/by-id/usb-ArduPilot_ARK_FPV*-if00 | head -1)")"
  elif [[ -e /dev/ttyACM0 ]]; then
    FCU_DEVICE="/dev/ttyACM0"
  else
    # If /dev/ttyTHS0 does not work, change to /dev/ttyTHS1 — some Orin NX carrier
    # boards map header pins 8 and 10 to THS1 instead of THS0.
    FCU_DEVICE="/dev/ttyTHS0"
  fi
fi

BAUDRATE="${BAUDRATE:-115200}"

MAVROS_UDP_HOST="${MAVROS_UDP_HOST:-127.0.0.1}"
MAVROS_UDP_PORT="${MAVROS_UDP_PORT:-14555}"
PING_MAVLINK_PORT="${PING_MAVLINK_PORT:-14556}"
# Laptop QGC — USB tether default: laptop .1, Jetson .2 on 192.168.137.0/24
QGC_UDP_HOST="${QGC_UDP_HOST:-192.168.137.1}"
QGC_UDP_PORT="${QGC_UDP_PORT:-14550}"
# Set QGC_UDP_BCAST=192.168.137.255 to also broadcast (Wi-Fi bench subnets)
QGC_UDP_BCAST="${QGC_UDP_BCAST:-}"

# ---------------------------------------------------------------------------

if ! command -v mavlink-routerd >/dev/null 2>&1; then
  echo "ERROR: mavlink-routerd not found."
  echo ""
  echo "Install with:"
  echo "  sudo apt update && sudo apt install mavlink-router"
  echo ""
  echo "Or build from: https://github.com/mavlink-router/mavlink-router"
  exit 1
fi

if [[ ! -e "${FCU_DEVICE}" ]]; then
  echo "ERROR: FCU device not found: ${FCU_DEVICE}"
  echo "  ls -l /dev/ark_fpv /dev/ttyACM* /dev/ttyTHS0 /dev/ttyTHS1"
  exit 1
fi

if fuser "${FCU_DEVICE}" >/dev/null 2>&1; then
  echo "ERROR: ${FCU_DEVICE} is already in use."
  echo "  Close QGroundControl if it has a direct USB link to the FCU."
  echo "  Use QGC UDP to <jetson-ip>:${QGC_UDP_PORT} instead."
  fuser -v "${FCU_DEVICE}" 2>&1 || true
  exit 1
fi

ROUTER_CONF="$(mktemp /tmp/marv-mavlink-router.XXXXXX.conf)"
cleanup() { rm -f "${ROUTER_CONF}"; }
trap cleanup EXIT

cat > "${ROUTER_CONF}" <<EOF
# Generated by start_mavlink_router.sh — FCU serial fan-out
[UartEndpoint fcu]
Device = ${FCU_DEVICE}
Baud = ${BAUDRATE}

# MAVROS on Jetson (MAVROS listens on this UDP port)
[UdpEndpoint mavros]
Mode = Normal
Address = ${MAVROS_UDP_HOST}
Port = ${MAVROS_UDP_PORT}

# mavlink_ping_bridge (separate port — do not share 14555 with MAVROS)
[UdpEndpoint ping_bridge]
Mode = Normal
Address = 127.0.0.1
Port = ${PING_MAVLINK_PORT}

# QGC on laptop — mavlink-router pushes TO laptop (QGC listens on port ${QGC_UDP_PORT})
[UdpEndpoint qgc_laptop]
Mode = Normal
Address = ${QGC_UDP_HOST}
Port = ${QGC_UDP_PORT}

# QGC can also connect TO Jetson on this port (optional second path)
[UdpEndpoint qgc_server]
Mode = Server
Address = 0.0.0.0
Port = ${QGC_UDP_PORT}
EOF

if [[ -n "${QGC_UDP_BCAST}" ]]; then
  cat >> "${ROUTER_CONF}" <<EOF

# QGC broadcast (e.g. Wi-Fi subnet)
[UdpEndpoint qgc_bcast]
Mode = Normal
Address = ${QGC_UDP_BCAST}
Port = ${QGC_UDP_PORT}
EOF
fi

echo "=== Marv mavlink-router bridge ==="
echo "  Config:  ${ROUTER_CONF}"
echo "  FCU:     ${FCU_DEVICE} @ ${BAUDRATE}"
echo "  MAVROS:  udp://@${MAVROS_UDP_HOST}:${MAVROS_UDP_PORT}"
echo "  QGC:     listen on laptop UDP port ${QGC_UDP_PORT} (stream from ${QGC_UDP_HOST})"
echo "           or connect TO <jetson-ip>:${QGC_UDP_PORT}"
echo "  Jetson:  $(hostname -I 2>/dev/null | awk '{print $1}')"
echo ""
echo "STARTUP ORDER:"
echo "  1) Run this script"
echo "  2) QGC connect — wait for parameters"
echo "  3) ~/marv_ws/scripts/run_prequal.sh"
echo ""
echo "Press Ctrl+C to stop."
echo ""

exec mavlink-routerd -c "${ROUTER_CONF}"
