#!/usr/bin/env python3
"""Generate Gazebo world SDF files for Marv missions (bb_worlds assets by default)."""

from __future__ import annotations

from pathlib import Path

WORLD_HEADER = """<?xml version="1.0"?>
<!-- Auto-generated by scripts/generate_worlds.py — do not edit by hand. -->
<sdf version="1.9">
  <world name="{world_name}">
    <scene>
      <ambient>0.01 0.01 0.01 1.0</ambient>
      <background>0.05 0.08 0.15 1.0</background>
      <shadows>true</shadows>
    </scene>
    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <!-- Required for ArduPilotPlugin JSON (imu_sensor -> imuMsgValid). -->
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <spherical_coordinates>
      <surface_model>EARTH_WGS84</surface_model>
      <world_frame_orientation>ENU</world_frame_orientation>
      <latitude_deg>1.309562</latitude_deg>
      <longitude_deg>103.7745783</longitude_deg>
      <elevation>0.0</elevation>
      <heading_deg>0.0</heading_deg>
    </spherical_coordinates>
    <light type="directional" name="sun1">
      <pose>50 0 150 0 0 0</pose>
      <diffuse>1 1 1 1</diffuse>
      <specular>0.1 0.1 0.1 1</specular>
      <direction>0.3 0.3 -1</direction>
      <cast_shadows>false</cast_shadows>
    </light>
    <light type="directional" name="sun_diffuse">
      <pose>-50 0 -150 0 0 0</pose>
      <diffuse>0.6 0.6 0.6 1</diffuse>
      <direction>-0.3 -0.3 -1</direction>
      <cast_shadows>false</cast_shadows>
    </light>
"""

WORLD_FOOTER = """
    <plugin filename="gz-sim-buoyancy-system" name="gz::sim::systems::Buoyancy">
      <graded_buoyancy>
        <default_density>1000</default_density>
        <density_change>
          <above_depth>0</above_depth>
          <density>1</density>
        </density_change>
      </graded_buoyancy>
    </plugin>
  </world>
</sdf>
"""

# bb_worlds robosub_2025_prequali.world layout (+X forward, z=-2 task depth).
PREQUAL_COURSE_POSE = '3 0 -2 0 0 0'
START_NOTE = (
    'Sub spawn: x=0 y=0 z=-2 (3 m behind gate). Layout matches bb_worlds '
    'robosub_2025_prequali.world.'
)

# Shared model URIs from https://github.com/BumblebeeAS/bb_worlds
M = {
    'pool': 'model://sp_swimming_pool',
    'waves': 'model://pool_waves',
    'prequal_course': 'model://marv_prequal_course_bb',
    'gate26': 'model://robosub26/gate',
    'gate25': 'model://robosub25/gate',
    'pillar': 'model://marv_bb_pillar',
    'path_straight': 'model://path_marker',
    'path_45cw': 'model://path_marker_45cw',
    'path_45ccw': 'model://path_marker_45ccw',
    'home_buoy': 'model://sauvc/sauvc_red_buoy',
    # Procedural fallback (no git-lfs / no bb_worlds install)
    'pool_simple': 'model://marv_pool',
    'gate_simple': 'model://marv_gate',
    'course_simple': 'model://marv_prequal_course',
    'pillar_simple': 'model://marv_yellow_pole',
    'path_simple': 'model://marv_path_marker',
    'home_simple': 'model://marv_home_buoy',
}

BB_POOL = [
    ('pool', M['pool'], '0 0 0 0 0 0'),
    ('surface', M['waves'], '0 0 0 0 0 0'),
]

SIMPLE_POOL = [
    ('pool', M['pool_simple'], '0 0 0 0 0 0'),
]


def bb_task(*props):
    return list(BB_POOL) + list(props)


def simple_task(*props):
    return list(SIMPLE_POOL) + list(props)


WORLD_SPECS = {
    # --- bb_worlds (default) ---
    'marv_pool': {
        'description': 'bb_worlds pool only.',
        'includes': BB_POOL,
    },
    'marv_prequal': {
        'description': f'Full pre-qual (bb_worlds). {START_NOTE}',
        'includes': bb_task(
            ('course', M['prequal_course'], PREQUAL_COURSE_POSE),
        ),
    },
    'marv_prequal_full': {
        'description': (
            f'Pre-qual (bb_worlds) + marv_auv embedded for ArduSub SITL. {START_NOTE}'
        ),
        'includes': bb_task(
            ('course', M['prequal_course'], PREQUAL_COURSE_POSE),
        ),
        'auv_include': ('marv_auv', 'model://marv_auv', '0 0 -2 0 0 0'),
    },
    'marv_prequal_sim': {
        'description': f'Stable Gazebo sim world (no pool_waves / LFS). {START_NOTE}',
        'includes': simple_task(
            ('course', M['course_simple'], '3 0 -1 0 0 0'),
        ),
    },
    'marv_task_wait_submerged': {
        'description': f'wait_submerged — pre-qual start. {START_NOTE}',
        'includes': bb_task(
            ('course', M['prequal_course'], PREQUAL_COURSE_POSE),
        ),
    },
    'marv_task_find_gate': {
        'description': 'find_gate — robosub26 gate ahead.',
        'includes': bb_task(
            ('gate', M['gate26'], '6 0 -2 0 0 0'),
        ),
    },
    'marv_task_traverse_gate': {
        'description': 'traverse_gate — gate at approach distance.',
        'includes': bb_task(
            ('gate', M['gate26'], '4 0 -2 0 0 0'),
        ),
    },
    'marv_task_pass_gate': {
        'description': 'pass_gate — gate close for timed pass.',
        'includes': bb_task(
            ('gate', M['gate26'], '2.5 0 -2 0 0 0'),
        ),
    },
    'marv_task_pass_gate_clear': {
        'description': 'pass_gate_clear — return-leg gate pass.',
        'includes': bb_task(
            ('gate', M['gate26'], '2.5 0 -2 0 0 0'),
        ),
    },
    'marv_task_transit': {
        'description': 'transit_forward — gate + marker 10 m ahead.',
        'includes': bb_task(
            ('course', M['prequal_course'], PREQUAL_COURSE_POSE),
        ),
    },
    'marv_task_find_marker': {
        'description': 'find_marker — pillar only, far ahead.',
        'includes': bb_task(
            ('marker', M['pillar'], '12 0 -2 0 0 0'),
        ),
    },
    'marv_task_approach_marker': {
        'description': 'approach_marker — pillar at medium range.',
        'includes': bb_task(
            ('marker', M['pillar'], '6 0 -2 0 0 0'),
        ),
    },
    'marv_task_circle_marker': {
        'description': 'circle_marker — pillar close for orbit.',
        'includes': bb_task(
            ('marker', M['pillar'], '3 0 -2 0 0 0'),
        ),
    },
    'marv_task_turn_around': {
        'description': 'turn_around — open pool after marker leg.',
        'includes': bb_task(
            ('marker', M['pillar'], '13 0 -2 0 0 0'),
        ),
    },
    'marv_task_find_return_gate': {
        'description': 'find_return_gate — gate behind after 180 deg turn.',
        'includes': bb_task(
            ('gate', M['gate26'], '-4 0 -2 0 0 3.14159'),
        ),
    },
    'marv_task_hold': {
        'description': 'hold — mission complete at start area.',
        'includes': bb_task(
            ('course', M['prequal_course'], PREQUAL_COURSE_POSE),
        ),
    },
    'marv_task_detect_path': {
        'description': 'detect_path — bb_worlds path markers.',
        'includes': bb_task(
            ('path_0', M['path_straight'], '3 0 -2 0 0 0'),
            ('path_1', M['path_straight'], '6 0 -2 0 0 0'),
            ('path_2', M['path_45cw'], '9 0 -2 0 0 0'),
            ('path_3', M['path_45ccw'], '12 1.5 -2 0 0 0'),
        ),
    },
    'marv_task_return_home': {
        'description': 'return_home — home buoy + gate.',
        'includes': bb_task(
            ('home', M['home_buoy'], '0 0 -2 0 0 0'),
            ('gate', M['gate26'], '8 0 -2 0 0 0'),
        ),
    },
    'marv_task_depth_hold': {
        'description': 'depth_hold — pool only.',
        'includes': BB_POOL,
    },
    'marv_competition': {
        'description': 'Full RoboSub 2026 pool (bb_worlds robosub_2026_pool.world layout).',
        'includes': bb_task(
            ('bins', 'model://robosub26/bins', '-3 2 -1.95 0 0 0'),
            ('torpedo_v1', 'model://robosub26/torpedo_panel_v1', '1 0 -2 0 0 0'),
            ('torpedo_v2', 'model://robosub26/torpedo_panel_v2', '3 0 -2 0 0 0'),
            ('gate', M['gate26'], '6 0 -2 0 0 0'),
            ('slalom', 'model://robosub26/slalom', '12 3 0 0 0 0'),
            ('table', 'model://robosub26/collection_table', '-6 -4.5 -1.1 0 0 0'),
            ('octagon', 'model://robosub26/octagon', '-6 -4.5 0 0 0 0'),
        ),
    },
    # --- Procedural fallback (use: mission:=prequal use_simple:=true) ---
    'marv_pool_simple': {
        'description': 'Procedural pool fallback (no bb_worlds meshes).',
        'includes': SIMPLE_POOL,
    },
    'marv_prequal_simple': {
        'description': f'Procedural pre-qual fallback. {START_NOTE}',
        'includes': simple_task(
            ('course', M['course_simple'], '3 0 -1 0 0 0'),
        ),
    },
    'marv_task_find_gate_simple': {
        'description': 'find_gate fallback.',
        'includes': simple_task(('gate', M['gate_simple'], '6 0 -1 0 0 0')),
    },
    'marv_task_traverse_gate_simple': {
        'description': 'traverse_gate fallback.',
        'includes': simple_task(('gate', M['gate_simple'], '4 0 -1 0 0 0')),
    },
    'marv_task_circle_marker_simple': {
        'description': 'circle_marker fallback.',
        'includes': simple_task(('marker', M['pillar_simple'], '3 0 -1 0 0 0')),
    },
}

MISSION_WORLD_MAP = {
    'prequal': 'marv_prequal',
    'wait_submerged': 'marv_task_wait_submerged',
    'find_gate': 'marv_task_find_gate',
    'traverse_gate': 'marv_task_traverse_gate',
    'pass_gate': 'marv_task_pass_gate',
    'pass_gate_clear': 'marv_task_pass_gate_clear',
    'transit_forward': 'marv_task_transit',
    'find_marker': 'marv_task_find_marker',
    'approach_marker': 'marv_task_approach_marker',
    'circle_marker': 'marv_task_circle_marker',
    'turn_around': 'marv_task_turn_around',
    'find_return_gate': 'marv_task_find_return_gate',
    'hold': 'marv_task_hold',
    'detect_path': 'marv_task_detect_path',
    'return_home': 'marv_task_return_home',
    'depth_hold': 'marv_task_depth_hold',
    'pool': 'marv_pool',
    'competition': 'marv_competition',
}

MISSION_WORLD_MAP_SIMPLE = {
    'prequal': 'marv_prequal_simple',
    'find_gate': 'marv_task_find_gate_simple',
    'traverse_gate': 'marv_task_traverse_gate_simple',
    'circle_marker': 'marv_task_circle_marker_simple',
    'pool': 'marv_pool_simple',
}


def render_include(name: str, uri: str, pose: str) -> str:
    return f"""    <include>
      <name>{name}</name>
      <uri>{uri}</uri>
      <pose>{pose}</pose>
    </include>
"""


def render_world(world_key: str, spec: dict) -> str:
    body = ''.join(
        render_include(name, uri, pose) for name, uri, pose in spec['includes']
    )
    auv = spec.get('auv_include')
    if auv:
        body += render_include(auv[0], auv[1], auv[2])
    desc = spec.get('description', '')
    comment = f'    <!-- {desc} -->\n' if desc else ''
    return (
        WORLD_HEADER.format(world_name=world_key)
        + comment
        + body
        + WORLD_FOOTER
    )


def main() -> None:
    pkg_dir = Path(__file__).resolve().parent.parent
    worlds_dir = pkg_dir / 'worlds'
    worlds_dir.mkdir(parents=True, exist_ok=True)

    for world_key, spec in WORLD_SPECS.items():
        out = worlds_dir / f'{world_key}.world'
        out.write_text(render_world(world_key, spec), encoding='utf-8')
        print(f'wrote {out.name}')

    manifest = worlds_dir / 'mission_world_map.yaml'
    lines = [
        '# Mission behavior -> Gazebo world (bb_worlds assets by default)\n',
        'default:\n',
    ]
    for mission, world in sorted(MISSION_WORLD_MAP.items()):
        lines.append(f'  {mission}: {world}\n')
    lines.append('\nsimple_fallback:\n')
    for mission, world in sorted(MISSION_WORLD_MAP_SIMPLE.items()):
        lines.append(f'  {mission}: {world}\n')
    manifest.write_text(''.join(lines), encoding='utf-8')
    print(f'wrote {manifest.name}')


if __name__ == '__main__':
    main()
